version: '3'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/myLoginRegisterDB
    networks:
      - my_network

  web:
    build: /home/yukta/Desktop/mern_app/login-and-register-app
    ports:
      - "5001:3000"
    depends_on:
      - backend
    networks:
      - my_network


  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network

volumes:
  mongo_data:

networks:
  my_network:
